import Nav from "@/components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import AlertComp from "@/components/Alert";
import { BsFacebook, BsGoogle, BsInstagram } from "react-icons/bs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Virtual Bazaar",
  description: "Generated by create next app",
  icons:{
    icon:'/icon.png'
  }
};



export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <AlertComp />
        <Nav />
        {children}
        <div className="footer-basic">
          <footer>
            <div className="social">
              <a href="#">
                <BsFacebook className="w-[40px] h-[40px] " />{" "}
              </a>
              <a href="#">
                <BsInstagram className="w-[40px] h-[40px] " />{" "}
              </a>
              <a href="#">
                <BsGoogle className="w-[40px] h-[40px] " />{" "}
              </a>
            </div>
            <ul className="list-inline">
              <li className="list-inline-item">
                <a href="#">Home</a>
              </li>
              <li className="list-inline-item">
                <a href="#">Services</a>
              </li>
              <li className="list-inline-item">
                <a href="#">About</a>
              </li>
              <li className="list-inline-item">
                <a href="#">Terms</a>
              </li>
              <li className="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p className="copyright">Company Name © 2018</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
